[package]
name = "tpch"
version = "0.4.0-SNAPSHOT"
authors = ["Andy Grove <andygrove73@gmail.com>"]
edition = "2018"

[dependencies]
ballista = { path="../../ballista" }

# use fork until https://github.com/apache/arrow/pull/9439 is merged
arrow = { git = "https://github.com/andygrove/arrow", rev="6e163c2" }
arrow-flight = { git = "https://github.com/andygrove/arrow", rev="6e163c2" }
datafusion = { git = "https://github.com/andygrove/arrow", rev="6e163c2" }
parquet = { git = "https://github.com/andygrove/arrow", rev="6e163c2" }

env_logger = "0.8"
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread", "sync"] }
structopt = "0.3"
