apiVersion: v1
kind: Pod
metadata:
  name: populate-data
spec:
  containers:
  - name: populate-data
    image: alpine:3.12.0
    command: ["https://raw.githubusercontent.com/ballista-compute/ballista/main/dev/download-nyctaxi-files.sh", "|", "bash", "-s", "/mnt"]
    # small file:
    #command: ["wget", "http://samplecsvs.s3.amazonaws.com/SacramentocrimeJanuary2006.csv", "-P", "/mnt"]
    volumeMounts:
    - mountPath: /mnt
      name: data
  restartPolicy: Never
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-pv-claim
