apiVersion: v1
kind: Service
metadata:
  name: ballista
  labels:
    app: ballista
spec:
  ports:
    - port: 50051
      name: flight
  clusterIP: None
  selector:
    app: ballista
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ballista
spec:
  serviceName: "ballista"
  replicas: 2
  selector:
    matchLabels:
      app: ballista
  template:
    metadata:
      labels:
        app: ballista
    spec:
      containers:
      - name: ballista
        image: ballistacompute/rust
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "128Mi"
        ports:
          - containerPort: 50051
            name: flight
        volumeMounts:
        - name: nyctaxi
          mountPath: /mnt/nyctaxi
      volumes:
      - name: nyctaxi
        hostPath:
          # change this to the path to the files on your host
          path: /mnt/nyctaxi
