apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-aggregate
spec:
  template:
    spec:
      containers:
        - name: parallel-aggregate
          image: ballistacompute/parallel-aggregate-rs
          # because we're testing in Minikube, we never want to pull remote images
          imagePullPolicy: Never
      restartPolicy: Never
  backoffLimit: 4